version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    expose:
      - 80
    ports:
      - 8081:80
    volumes:
      - ./public:/var/www/html

  php:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    expose:
      - 9000
    ports:
      - 8083:80
    volumes:
      - ./public:/var/www/html

  nginx-backend:
    build:
      context: .
      dockerfile: ./containers/nginx-backend/Dockerfile
    expose:
      - 80
    ports:
      - 8090:80
    volumes:
      - ./backend:/var/www/html

  php-backend:
    build:
      context: .
      dockerfile: ./containers/php-backend/Dockerfile
    expose:
      - 9000
    ports:
      - 8091:80
    volumes:
      - ./backend:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: enote
      MYSQL_USER: enote
      MYSQL_PASSWORD: enote
    ports:
      - 33006:3306

volumes:
  db-data:

networks:
  default:
    name: myapp-network
